Update Go to v1.22
test-network-function/pgt2acm pull request #3
Opened 2024-03-08 20:52 UTC by sebrandon1

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1902

2024-03-09 08:56 UTC, rdavid approved these changes

2024-03-13 22:31 UTC, edcdavid requested changes
ok pending rebase to pick up the CI

2024-03-14 23:07 UTC, edcdavid approved these changes

2024-03-16 19:39 UTC, rdavid approved these changes

2024-04-11 20:14 UTC, merged

2024-04-11 20:31 UTC, sebrandon1 commented
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1973